#include "mainwindow.h"

#include "QtGui/qmessagebox.h"

// Generated files
#include "mainwindow.moc"
#include "generated_code_DO_NOT_CHECK_THESE_IN/ui_mainwindow.h"

MainWindow::MainWindow() : ui( new Ui::MainWindow )
{
	ui->setupUi( this );

	// Example of an action. Moc MUST be deleted before this, it doesn't get
	// autogenerated for some reason.
	connect( ui->actionNew, SIGNAL( triggered() ), this, SLOT( on_actionnew_triggered() ) );
	//QObject::connect( actionExit, SIGNAL( triggered() ), MainWindow, SLOT( close() ) );
}

MainWindow::~MainWindow()
{
	delete ui;
}

void MainWindow::on_actionnew_triggered()
{
	QMessageBox::aboutQt( this, "About Qt" );
}